### ISSUE TITLE
Plato panics when opening books.

### ISSUE THREAD

**Issue by lacarthur** [baskerville/plato#383]
Hello, I've recently installed plato on my Kobo. I've run into a problem when I try to open some books I bought on the Kobo store. For some, but not all of them, opening the book in plato makes plato crash. I've done a factory reset and cleanly reinstalled plato, with default settings, and it does not change anything.

I have a Kobo Glo HD, my firmware version is 4.38.23171.
I have the most recent version of Plato (0.9.44).
Here is the logfile after I've tried opening a few books:

```
Add new entry: 54802B6A000A6AF8, 3b2eadf7-34ca-499c-9b05-919dea33ec78.
Add new entry: 54802B840053E9BA, 18abb7fa-432a-4239-99db-b71dbc47bbfa.
Add new entry: 54802C02003E0E6D, bdbfef45-6f34-4e87-b81c-00dd8a4d0322.
Add new entry: 54802C480058737B, 26d46481-83fd-4a96-a250-a535b755d1fe.
Can't retrieve 'OEBPS/kobo-locked.html' from the archive: specified file not found in archive.
Add new entry: 54802C740042F960, 5c434c88-4161-4464-bc95-9fa7f29bb984.
OK
Plato is running on a Kobo Glo HD.
The framebuffer resolution is 1072 by 1448.
thread '<unnamed>' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'main' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
OK
Plato is running on a Kobo Glo HD.
The framebuffer resolution is 1072 by 1448.
thread '<unnamed>' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'main' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
OK
Plato is running on a Kobo Glo HD.
The framebuffer resolution is 1072 by 1448.
thread '<unnamed>' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
3b2eadf7-34ca-499c-9b05-919dea33ec78
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'main' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
OK
Plato is running on a Kobo Glo HD.
The framebuffer resolution is 1072 by 1448.
thread '<unnamed>' panicked at crates/core/src/document/epub/mod.rs:720:58:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
Can't retrieve 'OEBPS/kobo-locked.html' from the archive: specified file not found in archive.
26d46481-83fd-4a96-a250-a535b755d1fe
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at crates/core/src/view/home/shelf.rs:91:62:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```
Am I doing something wrong?
Thanks,

**Comment by baskerville** [comment]
I tried with a few book previews and couldn't reproduce. Can you trigger the crash with a book preview?

**Comment by lacarthur** [comment]
Okay, interestingly, no. 
I've tried 7 different book previews, none of them trigger the crash. But out of my 10 books, only one of them does not crash. I doubt this is random.
I don't think it's related to file size either, because a 2.4M preview didn't crash, but a 2.1M full book crashed.
Let me know if you need me to test anything else.
